### ISSUE TITLE
Add a function to update many members at once to the LeanIMT implementation

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-kit#117]
**Is your feature request related to a problem? Please describe.**

The idea is to create a function called `updateMany`. This function can be useful to update many members at once. It should be more efficient to update N members using `updateMany` once than using the `update` function N times.

**Describe the solution you'd like**

It would be nice to have an implementation for TypeScript and Solidity similar to the `insertMany` function (links below). Something to remember is that the TypeScript implementation will be different from the Solidity implementation, as the data saved and optimizations in both environments are different.

**Additional context**

* `insertMany` TypeScript implementation: https://github.com/privacy-scaling-explorations/zk-kit/blob/main/packages/lean-imt/src/lean-imt.ts#L162
* `insertMany` Solidity implementation: https://github.com/privacy-scaling-explorations/zk-kit.solidity/blob/main/packages/lean-imt/contracts/InternalLeanIMT.sol#L91

**Comment by 0xjei** [comment]
Should we mark this as completed? See https://github.com/privacy-scaling-explorations/zk-kit/pull/104

**Comment by cedoor** [comment]
> @cedoor Should we mark this as completed? See #104

This is another task. That's the `insertMany` function. This would be the `updateMany`.

**Comment by ChinoCribioli** [comment]
Hi! I'd like to take this issue. :)
