### ISSUE TITLE
Make `babyjubjub`/`utils` packages browser-compatible

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-kit#144]
**Describe the improvement you're thinking about**

`Buffer` is an object only available on NodeJS. Although many bundlers add polyfills by default, some require configuration. Rollup itself could add a polyfill to the bundles, a browser-compatible package (e.g. [`buffer`](https://www.npmjs.com/package/buffer)) could be used, or `Buffer` could be replaced by `Uint8Array`, which is supported by both browsers and nodeJS.

**Comment by artwyman** [comment]
Context from the Zupass repo (which may be helpful, though you don't have to follow our lead): We polyfill Buffer, to the point that I didn't even realize it wasn't in browsers until recently.  There's also a "buffer" NPM package we've imported to provide a compatible version, which may be an alternative to polyfill or eliminating use of Buffer.

I've found Buffer nice to work with compared to UInt8Array, but it's pretty easy to convert between them whenever I need to if zk-kit starts to return only UInt8Array.

**Comment by cedoor** [comment]
Thanks! I think all these options need to be considered. The easiest solution looks like adding a polyfill. We're already using a Rollup plugin for the `iife` bundle here: https://github.com/privacy-scaling-explorations/zk-kit/blob/0b4ccbea88168d01cc518ed9b537f3479d6f7759/packages/utils/rollup.iife.config.ts#L38. We would just need to use in the other rollup configuration as well.

Replacing the `Buffer` functions we're using with `Uint8Array` could make the bundle lighter, but it also needs much more work and could introduce bugs.

On second thought, considering that in the future we may need other functions that `Buffer` already has, perhaps it is better to use a polyfill.
