### ISSUE TITLE
leBufferToBigint reverses its input

### ISSUE THREAD

**Issue by artwyman** [privacy-scaling-explorations/zk-kit#147]
**Describe the bug**

The buffer passed as argument to leBufferToBigint is reversed in-place, which could be a surprise for the caller.  This caused a lot of confusion when I was trying to test compatibility with circomlibjs by processing the same input in multiple ways.

**To Reproduce**
1. Make a buffer for input
2. Call `leBufferToBigint` on that input
3. Examine input buffer and see that its bytes have been reversed

I have a PR upcoming to fix this.  It'll include a unit test demonstrating this issue and the fix as soon as it's submitted.

**Expected behavior**
It's valid to argue that this is as-designed, since there's no documentation to demonstrate otherwise.  I argue that this is a potential source of bugs, and it's worth making an extra copy to avoid it.

**Additional context**
You can see some additional discussion on this issue between me and @cedoor on the #zk-kit channel of the PSE discord.
I work on Zupass at 0xPARC, and am in the process of evaluating zk-kit for use in some new PCDs.

**Comment by cedoor** [comment]
Hi @artwyman,  this is definitely a bug. It was expected that `reverse` would return a copy of the original inverted array!

Thanks 🙏🏽

**Comment by artwyman** [comment]
> Hi @artwyman, this is definitely a bug. It was expected that `reverse` would return a copy of the original inverted array!

Yeah, this is a bad default name in the library, from an older era where mutable values were more the norm.  There's a `toReversed()` which does what you wanted, but it's not available in earlier versions of JavaScript (in older browsers) so it doesn't seem safe to rely on.
