### ISSUE TITLE
eddsa-poseidon should return numbers as bigint not string

### ISSUE THREAD

**Issue by artwyman** [privacy-scaling-explorations/zk-kit#199]
**Is your feature request related to a problem? Please describe.**

All the functions in eddsa-poseidon return numeric values in stringified form, including bare `string` as well as `Point<string>` and `Signature<string>`.  In all cases, the values are `bigint` internally, and converted via `toString()` before return.

For a caller who wants to manipulate these numbers mathematically, this is a pessimization, since the caller will need to immediately parse the string back into a bigint.  

**Describe the solution you'd like**

Change these functions to return `bigint`.  Callers who want a string can call `toString()` and pay the same cost they're already paying.  Callers who want a `bigint` save that cost.

**Describe alternatives you've considered**
Leaving it as-is is the primary alternative.  It would avoid a breaking change.  The annoyance and cost is relatively small, but now is probably a better time for a breaking change than in future when there will be more users of a more stable package.

**Additional context**

I'm willing to implement this change, but this would be a breaking change, so I'm submitting this issue to spark discussion before I submit a PR.  Attn: @cedoor.

I don't know what other users of this library exist who could be broken by this.  If they're passing the values to another zk-kit function which accepts multiple input types (like a BigNumberish) their code would keep working.  If they're converting to a number via `BigInt()` that will also keep working, since the extra conversion is a nop.  However if they're using the values in a way which requires a string, they'd need to add an explicit call to toString().

**Comment by cedoor** [comment]
Hey @artwyman! I think this change is totally fine and it would be more consistent with `baby-jubjub`, which is already returning bigints.

> but now is probably a better time for a breaking change than in future when there will be more users of a more stable package.

Yes, there aren't many projects using these libraries and they aren't stable yet. So this is the right time.

Feel free to open a PR 👍🏽
