### ISSUE TITLE
Use `if` instead of `while` to increment `depth` in `InternalLeanIMT._insert()`

### ISSUE THREAD

**Issue by 0xbok** [privacy-scaling-explorations/zk-kit#213]
**Describe the improvement you're thinking about**
A new insertion can increase tree's depth by at most 1. We can be sure that this loop isn't executed twice:
https://github.com/privacy-scaling-explorations/zk-kit/blob/45739f6bed1acf31d8791b728346ea6ae9092915/packages/imt.sol/contracts/internal/InternalLeanIMT.sol#L49-L51

Thus, the `while` loop can be turned into an `if` condition saving gas. Add a comment explanation too.

**Additional context**
PSE audit.

**Comment by aguzmant103** [comment]
Retroactively giving out gitpoaps for 2024 contributors. Using this random issue to send them. Thanks again all for the contributions! :)

@gitpoap-bot @cedoor @vplasencia @0xjei @artwyman @ctrlc03 @rex4539 @alrevuelta @baumstern @0xbok @vimwitch
