### ISSUE TITLE
IMT's verifyProof function should be static

### ISSUE THREAD

**Issue by artwyman** [privacy-scaling-explorations/zk-kit#218]
**Describe the improvement you're thinking about**

The verifyProof function in both IMT (https://github.com/privacy-scaling-explorations/zk-kit/blob/main/packages/imt/src/imt/imt.ts#L299) and LeanIMT (https://github.com/privacy-scaling-explorations/zk-kit/blob/main/packages/imt/src/lean-imt/lean-imt.ts#L275) don't actually reference any state in the tree other than the `_hash` function.  I suggest separating this function from needing to be called on an instance object for two reasons:

- It's somewhat inconvenient to have to create a tree object in order to validate an unrelated proof.
- It's somewhat misleading that validating the proof checks the root in the proof, but not the root in the tree.  Without reading the code, it would be easy to assume it's validating that an element exists in this particular tree.

**Describe alternatives you've considered**
I'd suggest making a static function (or non-class function) which takes the hash as an argument.  There can also be a convenience function on the class itself which uses `this._hash` to call the static function.

Modifying the existing function to be static would be a breaking change, but if the static/free function is given a different name there's no need for that.

I can submit a PR for this after any discussion or feedback on the idea.

**Additional context**
This came up in the Zupass repo, where I ended up working around it by creating a new empty tree here: https://github.com/proofcarryingdata/zupass/pull/1564/files#diff-611d148c3a78ab428ec4a7fbb523eefddcf720a9833b214a25253b5b7ec651efR224

**Comment by cedoor** [comment]
Hey @artwyman, I agree that could definitely be static. If we want to avoid any breaking changes you could just add a static function with the same name (that shouldn't be a problem in JS).

I'd suggest using this signature: `static verifyProof<N>(proof: LeanIMTMerkleProof<N>, hash: LeanIMTHashFunction<N>)` to support TS generics.

Let me know if that works 👍🏽

**Comment by artwyman** [comment]
I didn't realize TypeScript allowed duplicate names for static and non-static functions, so yeah that'll make things easier.  That signature sounds right, though I'll need to experiment to properly understand the interaction of type parameters on the class vs. on the function.  I'll look into it, thanks.
