### ISSUE TITLE
TS `insert()` and `update()` doesn't check if the new leaf exists already

### ISSUE THREAD

**Issue by 0xbok** [privacy-scaling-explorations/zk-kit#243]
In Solidity version of LeanIMT, existing leaves cannot be inserted or updated, but TS version allows it.

https://github.com/privacy-scaling-explorations/zk-kit/blob/950dc5bd5f8f53069c12b56581ed63faa5382515/packages/imt/src/lean-imt/lean-imt.ts#L116

https://github.com/privacy-scaling-explorations/zk-kit/blob/950dc5bd5f8f53069c12b56581ed63faa5382515/packages/imt/src/lean-imt/lean-imt.ts#L156

https://github.com/privacy-scaling-explorations/zk-kit/blob/950dc5bd5f8f53069c12b56581ed63faa5382515/packages/imt/src/lean-imt/lean-imt.ts#L199

https://github.com/privacy-scaling-explorations/zk-kit/blob/950dc5bd5f8f53069c12b56581ed63faa5382515/packages/imt.sol/contracts/internal/InternalLeanIMT.sol#L40-L46

**Comment by aakansha1234** [comment]
Is it fine if I take up this issue?

**Comment by cedoor** [comment]
> Is it fine if I take up this issue?

Absolutely!

**Comment by aakansha1234** [comment]
I have added the check in insert and insertMany: 
https://github.com/privacy-scaling-explorations/zk-kit/compare/main...aakansha1234:zk-kit:insertcheck

I have a question for update function -
If we are doing a duplicate check on new leaf in update function, we will not be able to delete leaves as 0 will already be in existing leaves. 
How to resolve this?

**Comment by cedoor** [comment]
Hey @aakansha1234, I'd keep the `update` method without any check here. Sounds like a check that the extensions of this class need to add (e.g.[ `Group`](https://github.com/semaphore-protocol/semaphore/blob/a4a6837f5a0fbf6836f97aec108941c960710f64/packages/group/src/index.ts#L15)).

@0xbok What do you think?

**Comment by cedoor** [comment]
After discussing this with @0xbok, we decided to not check anything in this TS implementation.

Documentation needs to be added to the Solidity LeanIMT library tho, in order to make it clear that it is different from the TS one.
