### ISSUE TITLE
docs: add section to help choose merkle tree

### ISSUE THREAD

**Issue by sripwoud** [privacy-scaling-explorations/zk-kit#311]
There are several Merkle Tree "flavors:
- incremental
- sparse
- leant
- persistent
- ...

It would be helpful to write a comparison of of all them, answering questions like
- "when not to use"/"when to use"
- "used by?": protocol xyz, app xyz...
- include benchmarks: maybe one merkle tree is faster at generating a proof, but slower to update?

in order to help developers make a choice depending on their use case.

**Comment by prodasl** [comment]
Hi guys, here an PSE Core student, I want to help with this issue, please let me know if you can assign it to me.

**Comment by sripwoud** [comment]
Hi @prodasl 
Sure go ahead, I'll assign to you.
Btw I am personally looking forward for your answers, I created this issue because I don't know myself how to best choose out of these merkle tree variations :sweat_smile:
