### ISSUE TITLE
Define IMTNode explicitly instead of any

### ISSUE THREAD

**Issue by 0xDatapunk** [privacy-scaling-explorations/zk-kit#323]
https://github.com/privacy-scaling-explorations/zk-kit/blob/aa02c6df831e0b40f4cffc11ec5e92a1c8c319cb/packages/imt/src/types/index.ts#L4

does it make sense to define `export type IMTNode = number | string | bigint` directly instead of any?
All functions require such types anyway

**Comment by cedoor** [comment]
Duplicate: https://github.com/privacy-scaling-explorations/zk-kit/issues/339
