### ISSUE TITLE
Utility generic functions for "generateMerkleTree" and "generateMerkleProof". 

### ISSUE THREAD

**Issue by iskdrews** [privacy-scaling-explorations/zk-kit#34]
**Describe the bug**
We were using old `@zk-kit/protocols` package, and it was having a useful generic functions for "generateMerkleTree" and "generateMerkleProof" from `IncrementalMerkleTree` class. Since it's a deprecated package now we switched to use `@zk-kit/incremental-merkle-tree` package, which doesn't have those useful utility functions.

```javascript
// @zk-kit/protocol/src/utils.ts

import { IncrementalMerkleTree, MerkleProof } from "@zk-kit/incremental-merkle-tree"
import { poseidon } from "circomlibjs"
import { StrBigInt } from "./types"

/**
 * Creates a Merkle tree.
 * @param depth The depth of the tree.
 * @param zeroValue The zero value of the tree.
 * @param leaves The list of the leaves of the tree.
 * @returns The Merkle tree.
 */
export function generateMerkleTree(depth: number, zeroValue: StrBigInt, leaves: StrBigInt[]): IncrementalMerkleTree {
  const tree = new IncrementalMerkleTree(poseidon, depth, zeroValue, 2)

  for (const leaf of leaves) {
    tree.insert(BigInt(leaf))
  }

  return tree
}

/**
 * Creates a Merkle proof.
 * @param depth The depth of the tree.
 * @param zeroValue The zero value of the tree.
 * @param leaves The list of the leaves of the tree.
 * @param leaf The leaf for which Merkle proof should be created.
 * @returns The Merkle proof.
 */
export function generateMerkleProof(
  depth: number,
  zeroValue: StrBigInt,
  leaves: StrBigInt[],
  leaf: StrBigInt
): MerkleProof {
  if (leaf === zeroValue) throw new Error("Can't generate a proof for a zero leaf")

  const tree = generateMerkleTree(depth, zeroValue, leaves)

  const leafIndex = tree.leaves.indexOf(BigInt(leaf))

  if (leafIndex === -1) {
    throw new Error("The leaf does not exist")
  }

  const merkleProof = tree.createProof(leafIndex)

  merkleProof.siblings = merkleProof.siblings.map((s) => s[0])

  return merkleProof
}

```

Not sure if that would be a bug or it's intended for some reasons. The solution that we got now is to rewrite this code in our project. 

**Possible Solution**
Could these utility functions be added in `@zk-kit/incremental-merkle-tree` as a way to easily create an IncrementalMerkleTree and easily generate a proof without needing to rewrite this code again and installing `circomlibjs` directly in our project?

**Comment by cedoor** [comment]
Hi @iskdrews, that package was used by RLN and Semaphore. On Semaphore, it was replaced by `@semaphore-protocol/proof`. Are you using Semaphore?

The `circomlibjs` package should be external to the `@zk-kit/incremental-merkle-tree` library, which is independent of the hash function used in the Merkle tree.

**Comment by iskdrews** [comment]
> Hi @iskdrews, that package was used by RLN and Semaphore. On Semaphore, it was replaced by @semaphore-protocol/proof. Are you using Semaphore?

Hi @cedoor thanks for helping on that, yes I'm using `@semaphore-protocol/proof` to benefit from `generateProof()` function. But I didn't find a similar functions for generating an IncrementalMerkleTree `generateMerkleTree()` or for `generateMerkleProof()` from this generated tree. 
Also, `generateProof()` in `@semaphore-protocol/proof` is different because used for generating the full semaphore proof and it takes MerkleProof as a param input. Did you mean this?

> The `circomlibjs` package should be external to the @zk-kit/incremental-merkle-tree library, which is independent of the hash function used in the Merkle tree.
Do you mean its better handle creating the IncrementalMerkleTree directly in my project with the hash function that I need? So `@zk-kit/incremental-merkle-tree` has a generic class independent from the hash function. That's why I mentioned that this issue not a bug if that's the intention.

**Comment by cedoor** [comment]
> Also, generateProof() in @semaphore-protocol/proof is different because used for generating the full semaphore proof and it takes MerkleProof as a param input. Did you mean this?

Yes, have you tried (`@semaphore-protocol/group`](https://github.com/semaphore-protocol/semaphore/tree/main/packages/group)? It should make things easier.

> Do you mean its better handle creating the IncrementalMerkleTree directly in my project with the hash function that I need? So @zk-kit/incremental-merkle-tree has a generic class independent from the hash function. That's why I mentioned that this issue not a bug if that's the intention.

Yep, or you could use that package I mentioned maybe. Let me know if it makes sense!

**Comment by iskdrews** [comment]
@cedoor thanks so much, `@semaphore-protocol/group` would help me so much.  :100:
