### ISSUE TITLE
checking if newLeaf != this._nodes[0][index] first before update

### ISSUE THREAD

**Issue by 0xDatapunk** [privacy-scaling-explorations/zk-kit#340]
https://github.com/privacy-scaling-explorations/zk-kit/blob/c912111c134b6bbefe223bb61ba22f864036e9ba/packages/imt/src/imt.ts#L227

we can save some computation by checking if newLeaf != this._nodes[0][index] first?

**Comment by cedoor** [comment]
Yes, it makes sense!

**Comment by hannahredler** [comment]
Happy to take a look at this if it needs an owner 😄

**Comment by hannahredler** [comment]
@cedoor yeah! should be a quick one
