### ISSUE TITLE
Proposal: Modular solidity library contracts for flexibility

### ISSUE THREAD

**Issue by RayHuang880301** [privacy-scaling-explorations/zk-kit#66]
**Is your feature request related to a problem? Please describe.**
As a smart contract developer who uses the library contract from `zk-kit`, I hope I can choose to import this library as an internal function to my main contract or as a publicly deployed library. It may be used in different ways based on the requirements (like I want to save the deployment gas cost or run time gas cost...)

**Describe the solution you'd like**
I propose to modular the library contract by changing it to consist of public and internal libraries. The core logic is implemented in the internal function of the internal library and the public library contract just calls to the internal library.

For example, the `IncrementalBinaryTree.sol` library can be moved to an internal function library such as `IncrementalBinaryTreeInternal.sol`, and all the original implementation remains the same, just changing its naming and function visibility from `public` to `internal`
Then use the public `IncrementalBinaryTree.sol` to inherit `IncrementalBinaryTreeInternal.sol`, which means that the actual implementation is in `IncrementalBinaryTreeInternal.sol` and `IncrementalBinaryTree.sol` is only a public function to call the implementation in `IncrementalBinaryTreeInternal.sol`

 In practice, it is roughly as follows
<img width="697" alt="image" src="https://github.com/privacy-scaling-explorations/zk-kit/assets/84802160/c8eef336-1595-4c41-a556-a167393463ac">

There are some benefits to doing this
1. For developers to be more flexible, they can choose to use external libraries or internal libraries
2. For developers who want to use internal libraries to save run time gas costs, they can directly inherit `IncrementalBinaryTreeInternal.sol` to their main contract
3. Those who want to save deployment costs can directly use the deployed public shared `IncrementalBinaryTree` library which is provided the PSE website or github

In addition to the above, this approach maybe can be applied to many contracts in `zk-kit` generally, like `IncrementalQuinTree.sol`, `LazyMerkleTree.sol`... etc. 😉

**Comment by 0xjei** [comment]
> **Is your feature request related to a problem? Please describe.** As a smart contract developer who uses the library contract from `zk-kit`, I hope I can choose to import this library as an internal function to my main contract or as a publicly deployed library. It may be used in different ways based on the requirements (like I want to save the deployment gas cost or run time gas cost...)
> 
> **Describe the solution you'd like** I propose to modular the library contract by changing it to consist of public and internal libraries. The core logic is implemented in the internal function of the internal library and the public library contract just calls to the internal library.
> 
> For example, the `IncrementalBinaryTree.sol` library can be moved to an internal function library such as `IncrementalBinaryTreeInternal.sol`, and all the original implementation remains the same, just changing its naming and function visibility from `public` to `internal` Then use the public `IncrementalBinaryTree.sol` to inherit `IncrementalBinaryTreeInternal.sol`, which means that the actual implementation is in `IncrementalBinaryTreeInternal.sol` and `IncrementalBinaryTree.sol` is only a public function to call the implementation in `IncrementalBinaryTreeInternal.sol`
> 
> In practice, it is roughly as follows <img alt="image" width="697" src="https://private-user-images.githubusercontent.com/84802160/266795487-c8eef336-1595-4c41-a556-a167393463ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTE5NjgsIm5iZiI6MTcwMTI1MTY2OCwicGF0aCI6Ii84NDgwMjE2MC8yNjY3OTU0ODctYzhlZWYzMzYtMTU5NS00YzQxLWE1NTYtYTE2NzM5MzQ2M2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA5NTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMmNjYjMzZTEwN2I1OTAxNTM1M2ZhMDBhOWJmNzY3YmYxNWRkZDRiMTU5YTViNjdhN2JhN2FmMzUxZDE1YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9yAqoiJRq4C1pYhDxnhKrd01Ckpe1kSCJAwI-3dEIL0">
> 
> There are some benefits to doing this
> 
> 1. For developers to be more flexible, they can choose to use external libraries or internal libraries
> 2. For developers who want to use internal libraries to save run time gas costs, they can directly inherit `IncrementalBinaryTreeInternal.sol` to their main contract
> 3. Those who want to save deployment costs can directly use the deployed public shared `IncrementalBinaryTree` library which is provided the PSE website or github
> 
> In addition to the above, this approach maybe can be applied to many contracts in `zk-kit` generally, like `IncrementalQuinTree.sol`, `LazyMerkleTree.sol`... etc. 😉

Amazing, thanks @RayHuang880301. I will start working on it this week :)

**Comment by 0xjei** [comment]
@RayHuang880301 see #92
